# 小狸插件配置

# ── 必备生产力 ──
ENABLE_AI_SEARCH = True
ENABLE_CMD_EXECUTOR = True
ENABLE_FILE_MANAGER = True
ENABLE_CODE_EDITOR = True
ENABLE_GIT_TOOLS = True
ENABLE_FRONTEND_TESTER = True
ENABLE_NETWORK_TOOLS = True
ENABLE_SCHEDULER = True
ENABLE_SPEECH_RECOGNITION = True
ENABLE_TASK_MANAGER = True
ENABLE_TOOL_SEARCH = True
ENABLE_AUTO_ENGINEER = True
ENABLE_TERMINAL = True
ENABLE_OPERIT_BRIDGE = True
ENABLE_BROWSER_AUTO = True
ENABLE_GUI_AUTO = True
ENABLE_SUB_AGENT = True
ENABLE_WORKFLOW = True
ENABLE_MEMORY_PLUGIN = True
ENABLE_JSON_TOOLKIT = True
ENABLE_REGEX_TESTER = True
ENABLE_SNIPPET_MANAGER = True
ENABLE_MARKDOWN_TOOL = True
ENABLE_ID_GENERATOR = True
