# 小狸插件配置
# 自动生成于: 2026-04-25

ENABLE_AI_SEARCH = True
ENABLE_AUDIO_PLAYER = True
ENABLE_CMD_EXECUTOR = True
ENABLE_FILE_MANAGER = True
ENABLE_CODE_EDITOR = True
ENABLE_CODE_SEARCH = True
ENABLE_GIT_TOOLS = True
ENABLE_FRONTEND_TESTER = True
ENABLE_NETWORK_TOOLS = True
ENABLE_SCHEDULER = True
ENABLE_SPEECH_RECOGNITION = True
ENABLE_TASK_MANAGER = True
ENABLE_TOOL_SEARCH = True
